projects:
  "zowe/zowe-cli":
    unit:
      junit-artifact: zowe-cli.yml/ubuntu-22.04-20.x-results/unit
      lcov-artifact: zowe-cli.yml/ubuntu-22.04-20.x-results/unit/coverage
    integration:
      junit-artifact: zowe-cli.yml/ubuntu-22.04-20.x-results/integration
    system:
      test-count: npm-jest
  "zowe/cics-for-zowe-client#main":
    unit-cli:
      junit-artifact: main.yml/ubuntu-latest-20.x-results/cli/__tests__/__results__/unit
      lcov-artifact: main.yml/ubuntu-latest-20.x-results/cli/__tests__/__results__/unit/coverage
    unit-sdk:
      junit-artifact: main.yml/ubuntu-latest-20.x-results/sdk/__tests__/__results__/unit
      lcov-artifact: main.yml/ubuntu-latest-20.x-results/sdk/__tests__/__results__/unit/coverage
    unit-vsce:
      junit-artifact: main.yml/ubuntu-latest-20.x-results/vsce/__tests__/__results__/unit
    system:
      test-count: npm-jest:packages/cli,packages/sdk
  "zowe/zowe-cli-db2-plugin":
    unit:
      junit-artifact: zowe-cli-plugin.yml/ubuntu-latest-20.x-results/unit
      lcov-artifact: zowe-cli-plugin.yml/ubuntu-latest-20.x-results/unit/coverage
    system:
      test-count: npm-jest
  "zowe/zowe-cli-ftp-plugin":
    unit:
      junit-artifact: zowe-cli-plugin.yml/ubuntu-latest-20.x-results/unit
      lcov-artifact: zowe-cli-plugin.yml/ubuntu-latest-20.x-results/unit/coverage
    system:
      test-count: npm-jest
  "zowe/zowe-cli-mq-plugin":
    unit:
      junit-artifact: zowe-cli-plugin.yml/ubuntu-latest-20.x-results/unit
      lcov-artifact: zowe-cli-plugin.yml/ubuntu-latest-20.x-results/unit/coverage
    integration:
      junit-artifact: zowe-cli-plugin.yml/ubuntu-latest-20.x-results/integration
    system:
      test-count: npm-jest
  "zowe/zowe-explorer-vscode#main":
    unit:
      junit-artifact: zowe-explorer-ci.yml/zowe-explorer-results/results/unit
      lcov-artifact: zowe-explorer-ci.yml/zowe-explorer-results/results/unit/coverage
    unit-api:
      junit-artifact: zowe-explorer-ci.yml/zowe-explorer-api-results/unit
      lcov-artifact: zowe-explorer-ci.yml/zowe-explorer-api-results/unit/coverage
    unit-ftp:
      junit-artifact: zowe-explorer-ftp-ci.yml/zowe-explorer-ftp-extension-results/unit
      lcov-artifact: zowe-explorer-ftp-ci.yml/zowe-explorer-ftp-extension-results/unit/coverage
    integration:
      wdio-artifact: zowe-explorer-ci.yml/zowe-explorer-results/__tests__/__integration__/bdd/results
