name: Zowe CLI Coverage

on:
  schedule:
  - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: 'lts/*'
        cache: 'npm'

    - run: npm ci

    - run: |
        node scripts/coverage-report.js
        npx csv-to-markdown-table --delim ',' --headers < coverage-report.csv >> $GITHUB_STEP_SUMMARY
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: 'coverage-report'
        path: 'coverage-report.csv'
