name: Zowe CLI Bundle All

on:
  pull_request:
    paths-ignore:
      - '.github/workflows/zowe-cli-deploy-*.yaml'
      - 'scripts/deploy-*.js'
  schedule:
  - cron: '0 0 * * *'

jobs:
  build-v2-lts:
    if: ${{ github.event_name != 'pull_request' || startsWith(github.head_ref, 'v2') }}
    uses: ./.github/workflows/zowe-cli-bundle.yaml
    permissions:
      id-token: write
      pull-requests: write
    secrets:
      JF_ARTIFACTORY_TOKEN: ${{ secrets.JF_ARTIFACTORY_TOKEN }}
    with:
      dry-run: ${{ github.event_name != 'schedule' }}
      package-tag: zowe-v2-lts
      release-type: snapshot

  build-v3-lts:
    if: ${{ github.event_name != 'pull_request' || startsWith(github.head_ref, 'v3') }}
    uses: ./.github/workflows/zowe-cli-bundle.yaml
    permissions:
      id-token: write
      pull-requests: write
    secrets:
      JF_ARTIFACTORY_TOKEN: ${{ secrets.JF_ARTIFACTORY_TOKEN }}
    with:
      dry-run: ${{ github.event_name != 'schedule' }}
      package-tag: zowe-v3-lts
      release-type: snapshot

  # build-next:
  #   uses: ./.github/workflows/zowe-cli-bundle.yaml
  #   permissions:
  #     id-token: write
  #     pull-requests: write
  #   secrets:
  #     JF_ARTIFACTORY_TOKEN: ${{ secrets.JF_ARTIFACTORY_TOKEN }}
  #   with:
  #     dry-run: ${{ github.event_name != 'schedule' }}
  #     package-tag: next
  #     release-type: snapshot
